name: Deploy
on:
  push:
    branches:
      - main
#   schedule:
    # - cron: '0 4,5,6 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run docs:build --if-present

      - name: Download
        run: curl -o docs/.vitepress/dist/iptv.m3u https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          # cname: example.com # if wanna deploy to custom domain
